name: Terraform validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TERRAFORM_DOCS_VERSION: "v0.16.0"
  TFLINT_VERSION: "v0.36.2"
  DETECT_SECRETS_VERSION: "1.3.0"

jobs:
  terraform-validation:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-python@v3
        name: "SETUP: Python"

      - uses: actions/cache@v3.0.8
        id: cache-terraform-docs
        name: "CACHE: terraform-docs"
        with:
          path: |
            ~/terraform-docs/bin/
          key: ${{ runner.os }}-terraform_docs-${{ env.TERRAFORM_DOCS_VERSION }}
          restore-keys: |
            ${{ runner.os}}-terraform_docs-

      - shell: bash
        name: "INSTALL: terraform-docs"
        if: steps.cache-terraform-docs.output.cache-hit != 'true'
        run: |
          wget https://github.com/terraform-docs/terraform-docs/releases/download/${{ env.TERRAFORM_DOCS_VERSION }}/terraform-docs-${{ env.TERRAFORM_DOCS_VERSION }}-linux-amd64.tar.gz
          tar xvzf terraform-docs-${{ env.TERRAFORM_DOCS_VERSION }}-linux-amd64.tar.gz
          mkdir -p ~/terraform-docs/bin/
          install terraform-docs ~/terraform-docs/bin/

      - shell: bash
        name: "SETUP: terraform-docs path"
        run: echo '~/terraform-docs/bin/' >> $GITHUB_PATH

      - uses: actions/checkout@v3
        name: Checkout source code

      - uses: actions/cache@v3.0.8
        id: cache-pre-commit-dependencies
        name: "CACHE: pip and pre-commit dependencies"
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: ${{ runner.os }}-pip-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip-pre-commit-

      - uses: actions/cache@v3.0.8
        id: cache-tflint
        name: "CACHE: tflint"
        with:
          path: |
            ~/tflint/bin/
          key: ${{ runner.os }}-tflint-${{ env.TFLINT_VERSION }}
          restore-keys: |
            ${{ runner.os }}-tflint-

      - shell: bash
        name: "INSTALL: detect-secrets"
        run: |
          pip install detect-secrets==${{ env.DETECT_SECRETS_VERSION }}

      - shell: bash
        name: "INSTALL: tflint"
        if: steps.cache-tflint.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/terraform-linters/tflint/releases/download/${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip
          unzip tflint_linux_amd64.zip
          mkdir -p ~/tflint/bin/
          install tflint ~/tflint/bin/

      - shell: bash
        name: "SETUP: tflint path"
        run: echo '~/tflint/bin/' >> $GITHUB_PATH

      - uses: pre-commit/action@v3.0.0
        name: "RUN: pre-commit"
        env:
          AWS_DEFAULT_REGION: "eu-central-1"
